version: '3.8'
services:
    web:
        build:
            context: .
            dockerfile: ./docker/web/Dockerfile
        ports:
            - ${APP_PORT}:${APP_PORT}
        restart: unless-stopped
        depends_on:
            db:
                condition: service_started
        networks:
            - web
        volumes:
            - ${STRAVA_ACTIVITIES_CACHE_FOLDER}:/usr/src/app/.cache
        environment:
            - DATABASE_URL=${DATABASE_URL_DOCKER}
    db:
        image: percona:8.0
        command: ['--default_authentication_plugin=caching_sha2_password']
        platform: linux/amd64
        cap_add:
            - SYS_NICE
        restart: unless-stopped
        environment:
            - MYSQL_USER=${DB_USER}
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
            - MYSQL_PASSWORD=${DB_PASSWORD}
            - MYSQL_DATABASE=${DB_DATABASE}
        ports:
            - ${DB_PORT_EXT}:${DB_PORT_INT}
        volumes:
            - ./.mysql:/var/lib/mysql
            - ./docker/db/:/docker-entrypoint-initdb.d/
        networks:
            - web
    grafana:
        build:
            context: .
            dockerfile: ./grafana/Dockerfile
        restart: always
        environment:
            - DB_USER=${DB_USER}
            - DB_PASSWORD=${DB_PASSWORD}
            - DB_DATABASE=${DB_DATABASE}
            - DB_PORT_INT=${DB_PORT_INT}
            - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
            - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
        ports:
            - ${GRAFANA_EXTERNAL_PORT}:3000
        volumes:
            - ./.grafana:/var/lib/grafana
        networks:
            - web
networks:
    web:
