-- CreateTable
CREATE TABLE `Activity` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `strava_id` BIGINT NOT NULL,
    `name` VARCHAR(191) NOT NULL,
    `distance` DOUBLE NOT NULL,
    `moving_time` INTEGER NOT NULL,
    `elapsed_time` INTEGER NOT NULL,
    `total_elevation_gain` INTEGER NOT NULL,
    `type` VARCHAR(191) NOT NULL,
    `sport_type` VARCHAR(191) NOT NULL,
    `start_date` DATETIME(3) NOT NULL,
    `start_date_local` DATETIME(3) NOT NULL,
    `achievement_count` INTEGER NOT NULL,
    `kudos_count` INTEGER NOT NULL,
    `comment_count` INTEGER NOT NULL,
    `athlete_count` INTEGER NOT NULL,
    `photo_count` INTEGER NOT NULL,
    `average_speed` DOUBLE NULL,
    `max_speed` DOUBLE NULL,
    `average_cadence` INTEGER NULL,
    `average_temp` DOUBLE NULL,
    `average_watts` DOUBLE NULL,
    `max_watts` INTEGER NULL,
    `weighted_average_watts` INTEGER NULL,
    `kilojoules` DOUBLE NULL,
    `device_watts` BOOLEAN NULL,
    `has_heartrate` BOOLEAN NOT NULL,
    `average_heartrate` DOUBLE NULL,
    `max_heartrate` INTEGER NULL,
    `elev_high` DOUBLE NULL,
    `elev_low` DOUBLE NULL,
    `pr_count` INTEGER NOT NULL,
    `suffer_score` INTEGER NULL,
    `calories` INTEGER NULL,
    `external_id` VARCHAR(191) NULL,
    `device_name` VARCHAR(191) NULL,
    `description` VARCHAR(191) NULL,

    UNIQUE INDEX `Activity_strava_id_key`(`strava_id`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
