{
 "title": "Calories",
 "time": { "from": "2023-11-30T23:00:00.000Z", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "sport_type",
    "label": "Sport type",
    "query": "SELECT DISTINCT sport_type From Activity"
   },
   {
    "name": "regular_type",
    "label": "Type",
    "query": "SELECT DISTINCT type From Activity"
   },
   {
    "name": "workout_type",
    "label": "Workout type",
    "query": "SELECT DISTINCT \n    CASE \n        WHEN workout_type = 2 THEN 'Long run'\n        WHEN workout_type IN (1,11) THEN 'Race'\n        WHEN workout_type IN (12, 3) THEN 'Workout'\n        ELSE 'Other' \n    END AS workout_type_label\nFROM Activity \nWHERE workout_type IS NOT NULL \n  AND workout_type NOT IN (10, 0);"
   }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Duration per day",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "dataset": "stravaapp",
     "rawSql": "SELECT \n    DATE(start_date) AS \"time\",\n    SUM(elapsed_time) / 3600 AS duration_hours_per_day\nFROM stravaapp.Activity\nWHERE \n    (\"${sport_type:csv_string}\" = \"'All'\" OR sport_type IN (${sport_type:sqlstring})) AND\n    (\"${regular_type:csv_string}\" = \"'All'\" OR type IN (${regular_type:sqlstring})) AND\n    elapsed_time > 0\nGROUP BY DATE(start_date)\nORDER BY DATE(start_date)"
    }
   ]
  },
  {
   "title": "Activities number",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "stravaapp",
     "rawSql": "SELECT\nCOUNT(calories)\nFROM stravaapp.Activity\nWHERE \n(\"${sport_type:csv_string}\" = \"'All'\" OR sport_type IN (${sport_type:sqlstring})) AND\n(\"${regular_type:csv_string}\" = \"'All'\" OR type IN (${regular_type:sqlstring})) AND\nstart_date BETWEEN FROM_UNIXTIME(${__from} / 1000) AND FROM_UNIXTIME(${__to} / 1000) AND\ncalories > 0"
    }
   ]
  },
  {
   "title": "Average duration",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "stravaapp",
     "rawSql": "SELECT\n    AVG(elapsed_time) / 3600 AS avg_duration_hours\nFROM stravaapp.Activity\nWHERE \n    (\"${sport_type:csv_string}\" = \"'All'\" OR sport_type IN (${sport_type:sqlstring})) AND\n    (\"${regular_type:csv_string}\" = \"'All'\" OR type IN (${regular_type:sqlstring})) AND\n    start_date BETWEEN FROM_UNIXTIME(${__from} / 1000) AND FROM_UNIXTIME(${__to} / 1000) AND\n    elapsed_time > 0"
    }
   ]
  },
  { "title": "Calories", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Calories per day",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "dataset": "stravaapp",
     "rawSql": "SELECT calories, start_date AS \"time\"\nFROM stravaapp.Activity WHERE\n(\"${sport_type:csv_string}\" = \"'All'\" OR sport_type IN (${sport_type:sqlstring})) AND\n(\"${regular_type:csv_string}\" = \"'All'\" OR type IN (${regular_type:sqlstring})) AND\ncalories > 0"
    }
   ]
  },
  {
   "title": "Calories sum",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "stravaapp",
     "rawSql": "SELECT\nSUM(calories)\nFROM stravaapp.Activity\nWHERE \n(\"${sport_type:csv_string}\" = \"'All'\" OR sport_type IN (${sport_type:sqlstring})) AND\n(\"${regular_type:csv_string}\" = \"'All'\" OR type IN (${regular_type:sqlstring})) AND\nstart_date BETWEEN FROM_UNIXTIME(${__from} / 1000) AND FROM_UNIXTIME(${__to} / 1000) AND\ncalories > 0"
    }
   ]
  },
  {
   "title": "Calories min",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "stravaapp",
     "rawSql": "SELECT\nMIN(calories)\nFROM stravaapp.Activity\nWHERE \n(\"${sport_type:csv_string}\" = \"'All'\" OR sport_type IN (${sport_type:sqlstring})) AND\n(\"${regular_type:csv_string}\" = \"'All'\" OR type IN (${regular_type:sqlstring})) AND\nstart_date BETWEEN FROM_UNIXTIME(${__from} / 1000) AND FROM_UNIXTIME(${__to} / 1000) AND\ncalories > 0"
    }
   ]
  },
  {
   "title": "Calories max",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 5, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "stravaapp",
     "rawSql": "SELECT\nMAX(calories)\nFROM stravaapp.Activity\nWHERE \n(\"${sport_type:csv_string}\" = \"'All'\" OR sport_type IN (${sport_type:sqlstring})) AND\n(\"${regular_type:csv_string}\" = \"'All'\" OR type IN (${regular_type:sqlstring})) AND\nstart_date BETWEEN FROM_UNIXTIME(${__from} / 1000) AND FROM_UNIXTIME(${__to} / 1000) AND\ncalories > 0"
    }
   ]
  },
  {
   "title": "Calories avg",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 12, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "stravaapp",
     "rawSql": "SELECT\nAVG(calories)\nFROM stravaapp.Activity\nWHERE \n(\"${sport_type:csv_string}\" = \"'All'\" OR sport_type IN (${sport_type:sqlstring})) AND\n(\"${regular_type:csv_string}\" = \"'All'\" OR type IN (${regular_type:sqlstring})) AND\nstart_date BETWEEN FROM_UNIXTIME(${__from} / 1000) AND FROM_UNIXTIME(${__to} / 1000) AND\ncalories > 0"
    }
   ]
  },
  {
   "title": "avg calories in min/max",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "stravaapp",
     "rawSql": "SELECT\nMIN(calories) as min,\nMAX(calories) as max,\nAVG(calories) as avg\nFROM stravaapp.Activity\nWHERE \n(\"${sport_type:csv_string}\" = \"'All'\" OR sport_type IN (${sport_type:sqlstring})) AND\n(\"${regular_type:csv_string}\" = \"'All'\" OR type IN (${regular_type:sqlstring})) AND\nstart_date BETWEEN FROM_UNIXTIME(${__from} / 1000) AND FROM_UNIXTIME(${__to} / 1000) AND\ncalories > 0"
    }
   ]
  },
  { "title": "Per hour", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Calories per hour",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "dataset": "stravaapp",
     "rawSql": "SELECT \n    start_date AS \"time\",\n    calories / (elapsed_time / 3600) AS calories_per_hour\nFROM stravaapp.Activity\nWHERE \n    (\"${sport_type:csv_string}\" = \"'All'\" OR sport_type IN (${sport_type:sqlstring})) AND\n    (\"${regular_type:csv_string}\" = \"'All'\" OR type IN (${regular_type:sqlstring})) AND\n    calories > 0 AND\n    elapsed_time > 0"
    }
   ]
  },
  {
   "title": "Calories avg per hour",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 12, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "stravaapp",
     "rawSql": "SELECT\n    SUM(calories) / (SUM(elapsed_time) / 3600) AS avg_calories_per_hour\nFROM stravaapp.Activity\nWHERE \n    (\"${sport_type:csv_string}\" = \"'All'\" OR sport_type IN (${sport_type:sqlstring})) AND\n    (\"${regular_type:csv_string}\" = \"'All'\" OR type IN (${regular_type:sqlstring})) AND\n    start_date BETWEEN FROM_UNIXTIME(${__from} / 1000) AND FROM_UNIXTIME(${__to} / 1000) AND\n    calories > 0 AND\n    elapsed_time > 0"
    }
   ]
  },
  {
   "title": "avg calories in min/max per hour",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "stravaapp",
     "rawSql": "SELECT\n    MIN(calories / (elapsed_time / 3600)) AS min,\n    MAX(calories / (elapsed_time / 3600)) AS max,\n    SUM(calories) / (SUM(elapsed_time) / 3600) AS avg\nFROM stravaapp.Activity\nWHERE \n    (\"${sport_type:csv_string}\" = \"'All'\" OR sport_type IN (${sport_type:sqlstring})) AND\n    (\"${regular_type:csv_string}\" = \"'All'\" OR type IN (${regular_type:sqlstring})) AND\n    start_date BETWEEN FROM_UNIXTIME(${__from} / 1000) AND FROM_UNIXTIME(${__to} / 1000) AND\n    calories > 0 AND\n    elapsed_time > 0"
    }
   ]
  },
  { "title": "Calories per sport_type", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Calories per sport_type",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {
     "dataset": "mysql",
     "rawSql": "SELECT \n    sport_type, \n    SUM(calories) AS total_calories\nFROM stravaapp.Activity\nWHERE \n    (\"${sport_type:csv_string}\" = \"'All'\" OR sport_type IN (${sport_type:sqlstring})) AND\n    (\"${regular_type:csv_string}\" = \"'All'\" OR type IN (${regular_type:sqlstring})) AND\n    calories > 0\nGROUP BY sport_type\nORDER BY total_calories DESC"
    }
   ]
  },
  {
   "title": "Duration per sport_type",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 43 },
   "targets": [
    {
     "dataset": "mysql",
     "rawSql": "SELECT \n    sport_type, \n    SUM(elapsed_time) / 3600 AS total_duration_hours\nFROM stravaapp.Activity\nWHERE \n    (\"${sport_type:csv_string}\" = \"'All'\" OR sport_type IN (${sport_type:sqlstring})) AND\n    (\"${regular_type:csv_string}\" = \"'All'\" OR type IN (${regular_type:sqlstring})) AND\n    elapsed_time > 0\nGROUP BY sport_type\nORDER BY total_duration_hours DESC"
    }
   ]
  },
  {
   "title": "Calories per hour per sport_type",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 51 },
   "targets": [
    {
     "dataset": "mysql",
     "rawSql": "SELECT \n    sport_type, \n    SUM(calories) / (SUM(elapsed_time) / 3600) AS avg_calories_per_hour\nFROM stravaapp.Activity\nWHERE \n    (\"${sport_type:csv_string}\" = \"'All'\" OR sport_type IN (${sport_type:sqlstring})) AND\n    (\"${regular_type:csv_string}\" = \"'All'\" OR type IN (${regular_type:sqlstring})) AND\n    calories > 0 AND\n    elapsed_time > 0\nGROUP BY sport_type\nORDER BY avg_calories_per_hour DESC"
    }
   ]
  },
  {
   "title": "Avg calories per sport_type",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 59 },
   "targets": [
    {
     "dataset": "mysql",
     "rawSql": "SELECT \n    sport_type, \n    AVG(calories) AS avg_calories_per_workout\nFROM stravaapp.Activity\nWHERE \n    (\"${sport_type:csv_string}\" = \"'All'\" OR sport_type IN (${sport_type:sqlstring})) AND\n    (\"${regular_type:csv_string}\" = \"'All'\" OR type IN (${regular_type:sqlstring})) AND\n    calories > 0\nGROUP BY sport_type\nORDER BY avg_calories_per_workout DESC"
    }
   ]
  },
  {
   "title": "Avg duration per sport_type",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 67 },
   "targets": [
    {
     "dataset": "mysql",
     "rawSql": "SELECT \n    sport_type, \n    AVG(elapsed_time) / 3600 AS avg_duration_hours\nFROM stravaapp.Activity\nWHERE \n    (\"${sport_type:csv_string}\" = \"'All'\" OR sport_type IN (${sport_type:sqlstring})) AND\n    (\"${regular_type:csv_string}\" = \"'All'\" OR type IN (${regular_type:sqlstring})) AND\n    elapsed_time > 0\nGROUP BY sport_type\nORDER BY avg_duration_hours DESC"
    }
   ]
  },
  { "title": "Calories per type", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 } },
  {
   "title": "Calories per type",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 76 },
   "targets": [
    {
     "dataset": "mysql",
     "rawSql": "SELECT \n    type, \n    SUM(calories) AS total_calories\nFROM stravaapp.Activity\nWHERE \n    (\"${sport_type:csv_string}\" = \"'All'\" OR sport_type IN (${sport_type:sqlstring})) AND\n    (\"${regular_type:csv_string}\" = \"'All'\" OR type IN (${regular_type:sqlstring})) AND\n    calories > 0\nGROUP BY type\nORDER BY total_calories DESC"
    }
   ]
  },
  {
   "title": "Duration per type",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 84 },
   "targets": [
    {
     "dataset": "mysql",
     "rawSql": "SELECT \n    type, \n    SUM(elapsed_time) / 3600 AS total_duration_hours\nFROM stravaapp.Activity\nWHERE \n    (\"${sport_type:csv_string}\" = \"'All'\" OR sport_type IN (${sport_type:sqlstring})) AND\n    (\"${regular_type:csv_string}\" = \"'All'\" OR type IN (${regular_type:sqlstring})) AND\n    elapsed_time > 0\nGROUP BY type\nORDER BY total_duration_hours DESC"
    }
   ]
  },
  {
   "title": "Calories per hour per type",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 92 },
   "targets": [
    {
     "dataset": "mysql",
     "rawSql": "SELECT \n    type, \n    SUM(calories) / (SUM(elapsed_time) / 3600) AS avg_calories_per_hour\nFROM stravaapp.Activity\nWHERE \n    (\"${sport_type:csv_string}\" = \"'All'\" OR sport_type IN (${sport_type:sqlstring})) AND\n    (\"${regular_type:csv_string}\" = \"'All'\" OR type IN (${regular_type:sqlstring})) AND\n    calories > 0 AND\n    elapsed_time > 0\nGROUP BY type\nORDER BY avg_calories_per_hour DESC"
    }
   ]
  },
  {
   "title": "Avg calories per type",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 100 },
   "targets": [
    {
     "dataset": "mysql",
     "rawSql": "SELECT \n    type, \n    AVG(calories) AS avg_calories_per_workout\nFROM stravaapp.Activity\nWHERE \n    (\"${sport_type:csv_string}\" = \"'All'\" OR sport_type IN (${sport_type:sqlstring})) AND\n    (\"${regular_type:csv_string}\" = \"'All'\" OR type IN (${regular_type:sqlstring})) AND\n    calories > 0\nGROUP BY type\nORDER BY avg_calories_per_workout DESC"
    }
   ]
  },
  {
   "title": "Avg duration per type",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 108 },
   "targets": [
    {
     "dataset": "mysql",
     "rawSql": "SELECT \n    sport_type, \n    AVG(elapsed_time) / 3600 AS avg_duration_hours\nFROM stravaapp.Activity\nWHERE \n    (\"${sport_type:csv_string}\" = \"'All'\" OR sport_type IN (${sport_type:sqlstring})) AND\n    (\"${regular_type:csv_string}\" = \"'All'\" OR type IN (${regular_type:sqlstring})) AND\n    elapsed_time > 0\nGROUP BY sport_type\nORDER BY avg_duration_hours DESC"
    }
   ]
  }
 ]
}