{
 "title": "Distance",
 "time": { "from": "2023-11-30T11:00:00.000Z", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "sport_type",
    "label": "Sport type",
    "query": "SELECT DISTINCT sport_type From Activity"
   },
   {
    "name": "regular_type",
    "label": "Type",
    "query": "SELECT DISTINCT type From Activity"
   },
   {
    "name": "workout_type",
    "label": "Workout type",
    "query": "SELECT DISTINCT \n    CASE \n        WHEN workout_type = 2 THEN 'Long run'\n        WHEN workout_type IN (1,11) THEN 'Race'\n        WHEN workout_type IN (12, 3) THEN 'Workout'\n        ELSE 'Other' \n    END AS workout_type_label\nFROM Activity \nWHERE workout_type IS NOT NULL \n  AND workout_type NOT IN (10, 0);"
   },
   {
    "name": "trainer",
    "label": "Trainer",
    "query": "SELECT DISTINCT trainer From Activity"
   }
  ]
 },
 "panels": [
  {
   "title": "Distance per day",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "mysql",
     "rawSql": "SELECT \n    DATE(start_date) AS \"time\",\n    SUM(distance) / 1000 AS km_per_day\nFROM stravaapp.Activity\nWHERE \n    (\"${sport_type:csv_string}\" = \"'All'\" OR sport_type IN (${sport_type:sqlstring})) AND\n    (\"${regular_type:csv_string}\" = \"'All'\" OR type IN (${regular_type:sqlstring})) AND\n    (\"${trainer:csv_string}\" = \"'All'\" OR trainer IN (${trainer:sqlstring})) AND\n    (\"${workout_type:csv_string}\" = \"'All'\" OR workout_type IN (\n            CASE\n                WHEN \"${workout_type:csv_string}\" LIKE \"%Long run%\" THEN 2\n                WHEN \"${workout_type:csv_string}\" LIKE \"%Race%\" THEN 1\n                WHEN \"${workout_type:csv_string}\" LIKE \"%Workout%\" THEN 3\n                ELSE NULL\n            END\n        ) OR workout_type IN (\n            CASE\n                WHEN \"${workout_type:csv_string}\" LIKE \"%Race%\" THEN 11\n                WHEN \"${workout_type:csv_string}\" LIKE \"%Workout%\" THEN 12\n                ELSE NULL\n            END\n        )\n    ) AND\n    distance IS NOT NULL AND distance > 0\nGROUP BY DATE(start_date)\nORDER BY DATE(start_date)"
    }
   ]
  },
  {
   "title": "Total km per sport type",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "dataset": "mysql",
     "rawSql": "SELECT \n    sport_type, \n    SUM(distance) / 1000 AS total_km\nFROM stravaapp.Activity\nWHERE \n    (\"${sport_type:csv_string}\" = \"'All'\" OR sport_type IN (${sport_type:sqlstring})) AND\n    (\"${regular_type:csv_string}\" = \"'All'\" OR type IN (${regular_type:sqlstring})) AND\n    (\"${trainer:csv_string}\" = \"'All'\" OR trainer IN (${trainer:sqlstring})) AND\n    (\"${workout_type:csv_string}\" = \"'All'\" OR workout_type IN (\n            CASE\n                WHEN \"${workout_type:csv_string}\" LIKE \"%Long run%\" THEN 2\n                WHEN \"${workout_type:csv_string}\" LIKE \"%Race%\" THEN 1\n                WHEN \"${workout_type:csv_string}\" LIKE \"%Workout%\" THEN 3\n                ELSE NULL\n            END\n        ) OR workout_type IN (\n            CASE\n                WHEN \"${workout_type:csv_string}\" LIKE \"%Race%\" THEN 11\n                WHEN \"${workout_type:csv_string}\" LIKE \"%Workout%\" THEN 12\n                ELSE NULL\n            END\n        )\n    ) AND\n    distance IS NOT NULL AND distance > 0\nGROUP BY sport_type\nORDER BY total_km DESC"
    }
   ]
  },
  {
   "title": "Avg km per sport type",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "dataset": "mysql",
     "rawSql": "SELECT \n    sport_type, \n    AVG(distance) / 1000 AS avg_km_per_workout\nFROM stravaapp.Activity\nWHERE \n    (\"${sport_type:csv_string}\" = \"'All'\" OR sport_type IN (${sport_type:sqlstring})) AND\n    (\"${regular_type:csv_string}\" = \"'All'\" OR type IN (${regular_type:sqlstring})) AND\n    (\"${trainer:csv_string}\" = \"'All'\" OR trainer IN (${trainer:sqlstring})) AND\n    (\"${workout_type:csv_string}\" = \"'All'\" OR workout_type IN (\n            CASE\n                WHEN \"${workout_type:csv_string}\" LIKE \"%Long run%\" THEN 2\n                WHEN \"${workout_type:csv_string}\" LIKE \"%Race%\" THEN 1\n                WHEN \"${workout_type:csv_string}\" LIKE \"%Workout%\" THEN 3\n                ELSE NULL\n            END\n        ) OR workout_type IN (\n            CASE\n                WHEN \"${workout_type:csv_string}\" LIKE \"%Race%\" THEN 11\n                WHEN \"${workout_type:csv_string}\" LIKE \"%Workout%\" THEN 12\n                ELSE NULL\n            END\n        )\n    ) AND\n    distance IS NOT NULL AND distance > 0\nGROUP BY sport_type\nORDER BY avg_km_per_workout DESC"
    }
   ]
  },
  {
   "title": "Avg min/km",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "targets": [
    {
     "dataset": "mysql",
     "rawSql": "SELECT \n    start_date AS \"time\",\n    (elapsed_time / 60) / (distance / 1000) AS pace_min_per_km\nFROM stravaapp.Activity\nWHERE \n    (\"${sport_type:csv_string}\" = \"'All'\" OR sport_type IN (${sport_type:sqlstring})) AND\n    (\"${regular_type:csv_string}\" = \"'All'\" OR type IN (${regular_type:sqlstring})) AND\n    (\"${trainer:csv_string}\" = \"'All'\" OR trainer IN (${trainer:sqlstring})) AND\n    (\"${workout_type:csv_string}\" = \"'All'\" OR workout_type IN (\n            CASE\n                WHEN \"${workout_type:csv_string}\" LIKE \"%Long run%\" THEN 2\n                WHEN \"${workout_type:csv_string}\" LIKE \"%Race%\" THEN 1\n                WHEN \"${workout_type:csv_string}\" LIKE \"%Workout%\" THEN 3\n                ELSE NULL\n            END\n        ) OR workout_type IN (\n            CASE\n                WHEN \"${workout_type:csv_string}\" LIKE \"%Race%\" THEN 11\n                WHEN \"${workout_type:csv_string}\" LIKE \"%Workout%\" THEN 12\n                ELSE NULL\n            END\n        )\n    ) AND\n    distance IS NOT NULL AND distance > 0 AND\n    elapsed_time IS NOT NULL AND elapsed_time > 0\nORDER BY start_date"
    }
   ]
  }
 ]
}