apiVersion: 1

datasources:
  - name: mysql
    type: mysql
    url: db:${DB_PORT_INT}
    user: ${DB_USER}
    database: ${DB_DATABASE}
    access: proxy
    basicAuth: false
    withCredentials: false
    isDefault: true
    secureJsonData:
      password: ${DB_PASSWORD}
    version: 1
    editable: true
